import type { Messages } from "../types";

export const bn: Messages = {
  foundation: {
    eyebrow: "লিসান প্ল্যাটফর্ম",
    heading: "আরবি শেখার ভিত্তি তৈরি হচ্ছে",
    description:
      "বাংলাভাষী শিক্ষার্থীদের জন্য একটি সহজ, নিরাপদ ও বহুভাষিক শেখার অভিজ্ঞতা।",
    status: "পর্ব ০ · প্রযুক্তিগত ভিত্তি",
  },
  learner: {
    nav:{home:"হোম",learn:"শিখুন",review:"রিভিউ",practice:"অনুশীলন",tutor:"AI টিউটর",profile:"প্রোফাইল",settings:"সেটিংস",soon:"শিগগির আসছে",logout:"লগআউট"},
    onboarding:{eyebrow:"আপনার শেখার পথ",title:"আপনার জন্য শেখা সাজাই",intro:"চারটি ছোট ধাপে আপনার বর্তমান অবস্থা ও লক্ষ্য জানিয়ে দিন।",back:"পেছনে",next:"পরের ধাপ",finish:"শেখা শুরু করুন",saving:"সংরক্ষণ হচ্ছে…",step:"ধাপ",error:"তথ্য সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",minuteUnit:"মিনিট",questions:{level:"আরবি নিয়ে আপনার অভিজ্ঞতা কেমন?",goal:"আপনার প্রধান শেখার লক্ষ্য কী?",daily:"প্রতিদিন কত মিনিট শিখতে চান?",mode:"কোন ধরনের শেখার অভিজ্ঞতা চান?"},levels:{complete_beginner:"একদম নতুন",knows_some_letters:"কিছু অক্ষর চিনি",reads_slowly:"ধীরে পড়তে পারি",basic:"প্রাথমিক আরবি জানি",intermediate:"মধ্যম স্তর"},goals:{quranic:"কুরআনিক আরবি",conversation:"কথোপকথন",travel:"ভ্রমণ",work:"কাজ",school:"পড়াশোনা",general:"সাধারণ শিক্ষা"},modes:{standard:"স্ট্যান্ডার্ড",child:"শিশুবান্ধব"},recommendations:{arabic_alphabet:"আরবি বর্ণমালা",letter_review:"অক্ষর ঝালাই",reading_basics:"হারাকাত ও পড়ার ভিত্তি",basic_foundations:"প্রাথমিক ভিত্তি ঝালাই",intermediate_review:"মধ্যম স্তরের ঝালাই"}},
    dashboard:{eyebrow:"আজকের শেখা",greeting:"আসসালামু আলাইকুম",subtitle:"অল্প অল্প করে নিয়মিত এগিয়ে চলুন।",continue:"শেখা চালিয়ে যান",course:"বর্তমান কোর্স",currentPath:"বর্তমান অবস্থান",startingPoint:"প্রস্তাবিত শুরু",progress:"সামগ্রিক অগ্রগতি",todayGoal:"আজকের লক্ষ্য",streak:"ধারাবাহিকতা",xp:"XP",lessons:"সম্পন্ন পাঠ",words:"শেখা শব্দ",reviews:"রিভিউ বাকি",achievement:"সাম্প্রতিক অর্জন",emptyAchievement:"প্রথম পাঠ শেষ করলে আপনার অর্জন এখানে দেখা যাবে।",minutes:"মিনিট",days:"দিন",coursePreparing:"কোর্সের পাঠগুলো প্রস্তুত হচ্ছে।",viewCourse:"কোর্স দেখুন"},
    course:{eyebrow:"শেখার পথ",languages:"ভাষার পথ",path:"কোর্সের ধাপ",empty:"এই কোর্সের প্রথম লেভেল এখনো প্রকাশিত হয়নি। প্রস্তুত হলে এখানেই দেখা যাবে।",draftNotice:"কোর্সটি এখনো প্রস্তুতির পর্যায়ে আছে।",completed:"সম্পন্ন",current:"বর্তমান",available:"উন্মুক্ত",locked:"লক",lessonsSoon:"পাঠ শিগগির যোগ হবে",back:"ড্যাশবোর্ডে ফিরুন"},
    lesson:{back:"কোর্সে ফিরুন",previous:"আগের পাঠ",next:"পরের পাঠ",alreadyCompleted:"এই পাঠ সম্পন্ন হয়েছে",comingSoon:"শিগগির আসছে",audio:"অডিও",pronunciation:"উচ্চারণ অনুশীলন",check:"উত্তর যাচাই করুন",checking:"যাচাই হচ্ছে…",correct:"সঠিক উত্তর",incorrect:"উত্তরটি সঠিক হয়নি।",questionRequired:"পাঠ শেষ করার আগে প্রয়োজনীয় অনুশীলনগুলো সঠিকভাবে সম্পন্ন করুন।",complete:"পাঠ সম্পন্ন করুন",completing:"সংরক্ষণ হচ্ছে…",completed:"পাঠ সম্পন্ন",xp:"XP",error:"কাজটি সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।",isolated:"আলাদা",initial:"শুরু",medial:"মাঝে",final:"শেষে",formsLabel:"অক্ষরের রূপ",makhraj:"উচ্চারণের স্থান",pronunciationTip:"উচ্চারণের পরামর্শ",retry:"আবার চেষ্টা করুন",expected:"গ্রহণযোগ্য উত্তর",attempt:"চেষ্টা",unavailable:"এখনো চালু হয়নি",audioUnavailable:"এই অনুশীলনের অডিও এখনো যোগ করা হয়নি। কিছু শোনানো হয়েছে বলে ধরা হচ্ছে না।",knowIt:"মনে আছে",needReview:"আরও ঝালাই দরকার",reveal:"উত্তর দেখুন",moveUp:"ওপরে নিন",moveDown:"নিচে নিন",selectMatch:"মিল নির্বাচন করুন",typeAnswer:"আপনার উত্তর লিখুন",rateLimited:"অনেক দ্রুত চেষ্টা হয়েছে। একটু পরে আবার চেষ্টা করুন।"},
    profile:{eyebrow:"আপনার পরিচয়",title:"প্রোফাইল",subtitle:"আপনার নাম, ভাষা ও শেখার লক্ষ্য ঠিক রাখুন।",fullName:"পুরো নাম",displayName:"যে নামে ডাকব",email:"ইমেইল",avatar:"প্রোফাইল ছবি",nativeLanguage:"নিজের ভাষা",learningLanguage:"যে ভাষা শিখছেন",country:"দেশের কোড",timezone:"সময় অঞ্চল",learningGoal:"শেখার লক্ষ্য",dailyGoal:"দৈনিক লক্ষ্য",save:"পরিবর্তন সংরক্ষণ",saving:"সংরক্ষণ হচ্ছে…",success:"প্রোফাইল সংরক্ষণ হয়েছে।",error:"প্রোফাইল সংরক্ষণ করা যায়নি।",avatarComingSoon:"PNG · JPG · WebP — শিগগির আসছে",minuteUnit:"মিনিট"},
    settings:{eyebrow:"আপনার পছন্দ",title:"সেটিংস",subtitle:"ইন্টারফেস ও শেখার অভিজ্ঞতা নিজের মতো করুন।",language:"ইন্টারফেস ভাষা",mode:"শিক্ষার্থী মোড",dailyGoal:"দৈনিক লক্ষ্য",audio:"অডিও পছন্দ",voice:"ভয়েস পছন্দ",notifications:"নোটিফিকেশন",soon:"পরবর্তী পর্বে আসছে",save:"সেটিংস সংরক্ষণ",saving:"সংরক্ষণ হচ্ছে…",success:"সেটিংস সংরক্ষণ হয়েছে।",error:"সেটিংস সংরক্ষণ করা যায়নি।"}
  },
};
