import type { Messages } from "../types";

export const en: Messages = {
  foundation: {
    eyebrow: "Lisan platform",
    heading: "The Arabic learning foundation is taking shape",
    description:
      "A simple, safe, multilingual learning experience for Bangla-speaking students.",
    status: "Phase 0 · Technical foundation",
  },
  learner: {
    nav:{home:"Home",learn:"Learn",review:"Review",practice:"Practice",tutor:"AI Tutor",profile:"Profile",settings:"Settings",soon:"Coming soon",logout:"Log out"},
    onboarding:{eyebrow:"Your learning path",title:"Let's shape learning for you",intro:"Tell us where you are and what you want in four short steps.",back:"Back",next:"Next",finish:"Start learning",saving:"Saving…",step:"Step",error:"We could not save your choices. Try again.",minuteUnit:"minutes",questions:{level:"What is your experience with Arabic?",goal:"What is your primary learning goal?",daily:"How many minutes would you like to learn each day?",mode:"Which learning experience suits you?"},levels:{complete_beginner:"Complete Beginner",knows_some_letters:"Know Some Letters",reads_slowly:"Can Read Slowly",basic:"Basic Arabic",intermediate:"Intermediate"},goals:{quranic:"Quranic Arabic",conversation:"Conversation",travel:"Travel",work:"Work",school:"School",general:"General Learning"},modes:{standard:"Standard",child:"Child friendly"},recommendations:{arabic_alphabet:"Arabic Alphabet",letter_review:"Letter Review",reading_basics:"Harakat and Reading Basics",basic_foundations:"Basic Foundations Review",intermediate_review:"Intermediate Review"}},
    dashboard:{eyebrow:"Today's learning",greeting:"Assalamu alaikum",subtitle:"Small, consistent steps build lasting progress.",continue:"Continue Learning",course:"Current course",currentPath:"Current position",startingPoint:"Recommended start",progress:"Overall progress",todayGoal:"Today's goal",streak:"Daily streak",xp:"XP",lessons:"Lessons completed",words:"Words learned",reviews:"Reviews due",achievement:"Recent achievement",emptyAchievement:"Your achievements will appear here after your first completed lesson.",minutes:"minutes",days:"days",coursePreparing:"Course lessons are being prepared.",viewCourse:"View course"},
    course:{eyebrow:"Learning path",languages:"Language path",path:"Course path",empty:"The first published level is not available yet. It will appear here when it is ready.",draftNotice:"This course is still being prepared.",completed:"Completed",current:"Current",available:"Available",locked:"Locked",lessonsSoon:"Lessons coming soon",back:"Back to dashboard"},
    lesson:{back:"Back to course",previous:"Previous lesson",next:"Next lesson",alreadyCompleted:"Lesson completed",comingSoon:"Coming soon",audio:"Audio",pronunciation:"Pronunciation practice",check:"Check answer",checking:"Checking…",correct:"Correct",incorrect:"That answer is not correct. Try again.",questionRequired:"Answer the required question correctly before completing this lesson.",complete:"Complete lesson",completing:"Saving…",completed:"Lesson completed",xp:"XP",error:"We could not complete that action. Try again.",isolated:"Isolated",initial:"Initial",medial:"Medial",final:"Final",formsLabel:"Letter forms",makhraj:"Articulation point",pronunciationTip:"Pronunciation tip"},
    profile:{eyebrow:"Your identity",title:"Profile",subtitle:"Keep your name, languages, and learning goal up to date.",fullName:"Full name",displayName:"Preferred name",email:"Email",avatar:"Profile image",nativeLanguage:"Native language",learningLanguage:"Learning language",country:"Country code",timezone:"Timezone",learningGoal:"Learning goal",dailyGoal:"Daily goal",save:"Save changes",saving:"Saving…",success:"Profile saved.",error:"We could not save your profile.",avatarComingSoon:"PNG · JPG · WebP — coming soon",minuteUnit:"minutes"},
    settings:{eyebrow:"Your preferences",title:"Settings",subtitle:"Adjust your interface and learning experience.",language:"Interface language",mode:"Student mode",dailyGoal:"Daily goal",audio:"Audio preferences",voice:"Voice preferences",notifications:"Notifications",soon:"Coming in a later phase",save:"Save settings",saving:"Saving…",success:"Settings saved.",error:"We could not save settings."}
  },
};
