import "server-only";
import type {RowDataPacket} from "mysql2/promise";
import {getPool,withTransaction} from "@/lib/db/mysql";
import {createId} from "@/lib/auth/user-repository";
import {localDateKey} from "@/server/learner/validation";
import {arabicLetterSchema,parseLessonBlock,phraseSchema,vocabularySchema,type ArabicLetterContent,type PhraseContent,type VocabularyContent} from "./schemas";
import {canAccessLesson,firstIncompleteLesson,nextLessonId,type LessonSequenceItem} from "./progression";
import {getPublicExercises} from "@/server/exercises/service";import type {PublicExercise} from "@/server/exercises/contracts";

export type PublicBlock={id:string;type:string;position:number;required:boolean;payload:unknown;letter?:ArabicLetterContent;vocabulary?:VocabularyContent[];phrases?:PhraseContent[];exercise?:PublicExercise};
export type LessonView={id:string;title:string;courseSlug:string;courseName:string;unitName:string;levelName:string;progress:{completed:boolean;completedAt:string|null;position:number;total:number};previousLessonId:string|null;nextLessonId:string|null;nextUnlocked:boolean;blocks:PublicBlock[]};

const sequenceSql=`SELECT l.id,COALESCE(lp.status='completed',false) completed FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE lv.course_id=? AND l.status='published' ORDER BY lv.position,u.position,l.position`;
function sequence(rows:RowDataPacket[]):LessonSequenceItem[]{return rows.map(row=>({id:String(row.id),completed:Boolean(row.completed)}));}

export async function getLessonForLearner(userId:string,lessonId:string):Promise<LessonView|null>{
  const pool=await getPool();const[lessonRows]=await pool.execute<RowDataPacket[]>(`SELECT l.id,l.title,c.id courseId,c.slug courseSlug,c.name courseName,u.name unitName,lv.name levelName,lp.status progressStatus,lp.completed_at completedAt FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' JOIN courses c ON c.id=lv.course_id AND c.status='published' JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='active' LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.id=? AND l.status='published' LIMIT 1`,[userId,userId,lessonId]);
  const lesson=lessonRows[0];if(!lesson)return null;const[sequenceRows]=await pool.execute<RowDataPacket[]>(sequenceSql,[userId,lesson.courseId]);const items=sequence(sequenceRows);if(!canAccessLesson(items,lessonId))return null;
  const[blockRows]=await pool.execute<RowDataPacket[]>("SELECT id,block_type blockType,position,schema_version schemaVersion,required,content FROM lesson_blocks WHERE lesson_id=? AND status='published' ORDER BY position",[lessonId]);
  const exercises=await getPublicExercises(userId,lessonId);const blocks:PublicBlock[]=[];for(const row of blockRows){const raw=typeof row.content==="string"?JSON.parse(row.content):row.content;const parsed=parseLessonBlock(String(row.blockType),{...raw,schemaVersion:Number(row.schemaVersion)});if(!parsed)continue;const block:PublicBlock={id:String(row.id),type:parsed.type,position:Number(row.position),required:Boolean(row.required),payload:parsed.payload};
    const arabicPayload=parsed.payload as{letterKey?:string;exampleWordKey?:string};if(parsed.type==="arabic_text"&&arabicPayload.letterKey){const[rows]=await pool.execute<RowDataPacket[]>("SELECT stable_key stableKey,character,arabic_name arabicName,bangla_pronunciation banglaPronunciation,english_transliteration englishTransliteration,bangla_sound_explanation banglaSoundExplanation,isolated_form isolatedForm,initial_form initialForm,medial_form medialForm,final_form finalForm,makhraj_region makhrajRegion,makhraj_subregion makhrajSubregion,makhraj_explanation_bn makhrajExplanationBangla,pronunciation_tip_bn pronunciationTipBangla,position FROM arabic_letters WHERE stable_key=? LIMIT 1",[arabicPayload.letterKey]);const letter=arabicLetterSchema.safeParse(rows[0]);if(!letter.success)continue;block.letter=letter.data;}
    if(parsed.type==="vocabulary"||(parsed.type==="arabic_text"&&arabicPayload.exampleWordKey)){const vocabularyPayload=parsed.payload as{vocabularyKeys?:string[]};const keys=parsed.type==="vocabulary"?vocabularyPayload.vocabularyKeys??[]:[arabicPayload.exampleWordKey!];const[rows]=await pool.query<RowDataPacket[]>("SELECT stable_key stableKey,word,word_with_diacritics wordWithDiacritics,bangla_pronunciation banglaPronunciation,bangla_meaning banglaMeaning,english_meaning englishMeaning,transliteration,part_of_speech partOfSpeech,root,difficulty,example_sentence exampleSentence FROM vocabulary_items WHERE stable_key IN (?)",[keys]);block.vocabulary=rows.map(row=>vocabularySchema.parse(row));}
    if(parsed.type==="phrase"){const phraseKeys=(parsed.payload as{phraseKeys:string[]}).phraseKeys;const[rows]=await pool.query<RowDataPacket[]>("SELECT stable_key stableKey,text,text_with_diacritics textWithDiacritics,bangla_pronunciation banglaPronunciation,bangla_meaning banglaMeaning,english_meaning englishMeaning,usage_note_bn usageNoteBangla,difficulty FROM phrases WHERE stable_key IN (?)",[phraseKeys]);const byKey=new Map(rows.map(row=>[String(row.stableKey),phraseSchema.parse(row)]));block.phrases=phraseKeys.flatMap((phraseKey:string)=>byKey.get(phraseKey)??[]);}
    if(parsed.type==="exercise"){const exerciseKey=(parsed.payload as{exerciseKey:string}).exerciseKey;block.exercise=exercises.get(exerciseKey);if(!block.exercise)continue;}
    blocks.push(block);
  }
  const index=items.findIndex(item=>item.id===lessonId),next=nextLessonId(items,lessonId);return{id:String(lesson.id),title:String(lesson.title),courseSlug:String(lesson.courseSlug),courseName:String(lesson.courseName),unitName:String(lesson.unitName),levelName:String(lesson.levelName),progress:{completed:lesson.progressStatus==="completed",completedAt:lesson.completedAt?new Date(lesson.completedAt).toISOString():null,position:index+1,total:items.length},previousLessonId:index>0?items[index-1].id:null,nextLessonId:next,nextUnlocked:Boolean(next&&canAccessLesson(items,next)),blocks};
}

export async function completeLesson(userId:string,lessonId:string,now=new Date()){return withTransaction(async connection=>{const[lessonRows]=await connection.execute<RowDataPacket[]>(`SELECT l.id,l.xp_reward xpReward,l.completion_rule completionRule,c.id courseId,e.id enrollmentId,u.id unitId,usr.timezone FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' JOIN courses c ON c.id=lv.course_id AND c.status='published' JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='active' JOIN users usr ON usr.id=e.user_id AND usr.role='student' AND usr.status='active' WHERE l.id=? AND l.status='published' FOR UPDATE`,[userId,lessonId]);const lesson=lessonRows[0];if(!lesson)throw new Error("LESSON_NOT_AVAILABLE");const[seqRows]=await connection.execute<RowDataPacket[]>(sequenceSql,[userId,lesson.courseId]);const items=sequence(seqRows);if(!canAccessLesson(items,lessonId))throw new Error("LESSON_LOCKED");const wasCompleted=items.find(item=>item.id===lessonId)?.completed??false;
    const rule=(typeof lesson.completionRule==="string"?JSON.parse(lesson.completionRule):lesson.completionRule??{}) as{requiredExercisesAttempted?:boolean;requiredExercisesCorrect?:boolean;minimumScorePercent?:number};const[exerciseStats]=await connection.execute<RowDataPacket[]>(`SELECT COUNT(*) requiredCount,SUM(CASE WHEN a.attempted=1 THEN 1 ELSE 0 END) attemptedCount,SUM(CASE WHEN a.correct=1 THEN 1 ELSE 0 END) correctCount,COALESCE(ROUND(AVG(COALESCE(a.bestScore,0))),100) scorePercent FROM exercises e LEFT JOIN (SELECT exercise_id,1 attempted,MAX(correct) correct,MAX(score) bestScore FROM exercise_attempts WHERE user_id=? GROUP BY exercise_id) a ON a.exercise_id=e.id WHERE e.lesson_id=? AND e.required=true AND e.status='published'`,[userId,lessonId]);const stats=exerciseStats[0],requiredCount=Number(stats.requiredCount??0),attemptedCount=Number(stats.attemptedCount??0),correctCount=Number(stats.correctCount??0),scorePercent=requiredCount?Number(stats.scorePercent??0):100;if(rule.requiredExercisesAttempted&&attemptedCount<requiredCount)throw new Error("REQUIRED_EXERCISE_INCOMPLETE");if(rule.requiredExercisesCorrect&&correctCount<requiredCount)throw new Error("REQUIRED_EXERCISE_INCORRECT");if(scorePercent<Number(rule.minimumScorePercent??0))throw new Error("MINIMUM_SCORE_NOT_MET");
    if(!wasCompleted){await connection.execute("INSERT INTO lesson_progress (id,user_id,lesson_id,status,started_at,completed_at,score_percent) VALUES (?,?,?,'completed',?,?,?) ON DUPLICATE KEY UPDATE status='completed',started_at=COALESCE(started_at,VALUES(started_at)),completed_at=COALESCE(completed_at,VALUES(completed_at)),score_percent=VALUES(score_percent)",[createId(),userId,lessonId,now,now,scorePercent]);await connection.execute("INSERT IGNORE INTO xp_transactions (id,user_id,amount,reason,source_type,source_id) VALUES (?,?,?,'lesson_completion','lesson',?)",[createId(),userId,Number(lesson.xpReward),lessonId]);const date=localDateKey(now,String(lesson.timezone));await connection.execute("INSERT INTO daily_learning_activities (id,user_id,activity_date,timezone,minutes,lessons_completed,words_learned,exercise_attempts) VALUES (?,?,?,?,0,1,0,0) ON DUPLICATE KEY UPDATE lessons_completed=lessons_completed+1",[createId(),userId,date,lesson.timezone]);}
    const completedItems=items.map(item=>item.id===lessonId?{...item,completed:true}:item),next=firstIncompleteLesson(completedItems);await connection.execute("UPDATE course_enrollments SET current_lesson_id=?,completed_at=? WHERE id=?",[next,next?null:now,lesson.enrollmentId]);return{completed:true,firstCompletion:!wasCompleted,xpAwarded:wasCompleted?0:Number(lesson.xpReward),nextLessonId:next,scorePercent};});}
