import "server-only";
import type {RowDataPacket} from "mysql2/promise";
import {getPool,withTransaction} from "@/lib/db/mysql";
import {createId} from "@/lib/auth/user-repository";
import {localDateKey} from "@/server/learner/validation";
import {arabicLetterSchema,parseLessonBlock,phraseSchema,toPublicMultipleChoice,vocabularySchema,multipleChoicePrivateSchema,type ArabicLetterContent,type MultipleChoicePrivate,type PhraseContent,type VocabularyContent} from "./schemas";
import {canAccessLesson,firstIncompleteLesson,nextLessonId,type LessonSequenceItem} from "./progression";

export type PublicBlock={id:string;type:string;position:number;required:boolean;payload:unknown;letter?:ArabicLetterContent;vocabulary?:VocabularyContent[];phrases?:PhraseContent[]};
export type LessonView={id:string;title:string;courseSlug:string;courseName:string;unitName:string;levelName:string;progress:{completed:boolean;completedAt:string|null;position:number;total:number};previousLessonId:string|null;nextLessonId:string|null;nextUnlocked:boolean;blocks:PublicBlock[]};

const sequenceSql=`SELECT l.id,COALESCE(lp.status='completed',false) completed FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE lv.course_id=? AND l.status='published' ORDER BY lv.position,u.position,l.position`;
function sequence(rows:RowDataPacket[]):LessonSequenceItem[]{return rows.map(row=>({id:String(row.id),completed:Boolean(row.completed)}));}

export async function getLessonForLearner(userId:string,lessonId:string):Promise<LessonView|null>{
  const pool=await getPool();const[lessonRows]=await pool.execute<RowDataPacket[]>(`SELECT l.id,l.title,c.id courseId,c.slug courseSlug,c.name courseName,u.name unitName,lv.name levelName,lp.status progressStatus,lp.completed_at completedAt FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' JOIN courses c ON c.id=lv.course_id AND c.status='published' JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='active' LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.id=? AND l.status='published' LIMIT 1`,[userId,userId,lessonId]);
  const lesson=lessonRows[0];if(!lesson)return null;const[sequenceRows]=await pool.execute<RowDataPacket[]>(sequenceSql,[userId,lesson.courseId]);const items=sequence(sequenceRows);if(!canAccessLesson(items,lessonId))return null;
  const[blockRows]=await pool.execute<RowDataPacket[]>("SELECT id,block_type blockType,position,schema_version schemaVersion,required,content FROM lesson_blocks WHERE lesson_id=? AND status='published' ORDER BY position",[lessonId]);
  const blocks:PublicBlock[]=[];for(const row of blockRows){const raw=typeof row.content==="string"?JSON.parse(row.content):row.content;const parsed=parseLessonBlock(String(row.blockType),{...raw,schemaVersion:Number(row.schemaVersion)});if(!parsed)continue;const block:PublicBlock={id:String(row.id),type:parsed.type,position:Number(row.position),required:Boolean(row.required),payload:parsed.type==="multiple_choice"?toPublicMultipleChoice(parsed.payload as MultipleChoicePrivate):parsed.payload};
    const arabicPayload=parsed.payload as{letterKey?:string;exampleWordKey?:string};if(parsed.type==="arabic_text"&&arabicPayload.letterKey){const[rows]=await pool.execute<RowDataPacket[]>("SELECT stable_key stableKey,character,arabic_name arabicName,bangla_pronunciation banglaPronunciation,english_transliteration englishTransliteration,bangla_sound_explanation banglaSoundExplanation,isolated_form isolatedForm,initial_form initialForm,medial_form medialForm,final_form finalForm,makhraj_region makhrajRegion,makhraj_subregion makhrajSubregion,makhraj_explanation_bn makhrajExplanationBangla,pronunciation_tip_bn pronunciationTipBangla,position FROM arabic_letters WHERE stable_key=? LIMIT 1",[arabicPayload.letterKey]);const letter=arabicLetterSchema.safeParse(rows[0]);if(!letter.success)continue;block.letter=letter.data;}
    if(parsed.type==="vocabulary"||(parsed.type==="arabic_text"&&arabicPayload.exampleWordKey)){const vocabularyPayload=parsed.payload as{vocabularyKeys?:string[]};const keys=parsed.type==="vocabulary"?vocabularyPayload.vocabularyKeys??[]:[arabicPayload.exampleWordKey!];const[rows]=await pool.query<RowDataPacket[]>("SELECT stable_key stableKey,word,word_with_diacritics wordWithDiacritics,bangla_pronunciation banglaPronunciation,bangla_meaning banglaMeaning,english_meaning englishMeaning,transliteration,part_of_speech partOfSpeech,root,difficulty,example_sentence exampleSentence FROM vocabulary_items WHERE stable_key IN (?)",[keys]);block.vocabulary=rows.map(row=>vocabularySchema.parse(row));}
    if(parsed.type==="phrase"){const phraseKeys=(parsed.payload as{phraseKeys:string[]}).phraseKeys;const[rows]=await pool.query<RowDataPacket[]>("SELECT stable_key stableKey,text,text_with_diacritics textWithDiacritics,bangla_pronunciation banglaPronunciation,bangla_meaning banglaMeaning,english_meaning englishMeaning,usage_note_bn usageNoteBangla,difficulty FROM phrases WHERE stable_key IN (?)",[phraseKeys]);const byKey=new Map(rows.map(row=>[String(row.stableKey),phraseSchema.parse(row)]));block.phrases=phraseKeys.flatMap((phraseKey:string)=>byKey.get(phraseKey)??[]);}
    blocks.push(block);
  }
  const index=items.findIndex(item=>item.id===lessonId),next=nextLessonId(items,lessonId);return{id:String(lesson.id),title:String(lesson.title),courseSlug:String(lesson.courseSlug),courseName:String(lesson.courseName),unitName:String(lesson.unitName),levelName:String(lesson.levelName),progress:{completed:lesson.progressStatus==="completed",completedAt:lesson.completedAt?new Date(lesson.completedAt).toISOString():null,position:index+1,total:items.length},previousLessonId:index>0?items[index-1].id:null,nextLessonId:next,nextUnlocked:Boolean(next&&canAccessLesson(items,next)),blocks};
}

export async function scoreMultipleChoice(userId:string,input:{lessonId:string;blockId:string;selectedOptionId:string}){const pool=await getPool();const lesson=await getLessonForLearner(userId,input.lessonId);if(!lesson||!lesson.blocks.some(block=>block.id===input.blockId&&block.type==="multiple_choice"))throw new Error("QUESTION_NOT_AVAILABLE");const[rows]=await pool.execute<RowDataPacket[]>("SELECT content,schema_version schemaVersion FROM lesson_blocks WHERE id=? AND lesson_id=? AND block_type='multiple_choice' AND status='published' LIMIT 1",[input.blockId,input.lessonId]);const row=rows[0];if(!row)throw new Error("QUESTION_NOT_AVAILABLE");const raw=typeof row.content==="string"?JSON.parse(row.content):row.content;const payload=multipleChoicePrivateSchema.parse({...raw,schemaVersion:Number(row.schemaVersion)});if(!payload.options.some(option=>option.id===input.selectedOptionId))throw new Error("INVALID_OPTION");const correct=input.selectedOptionId===payload.correctOptionId;await pool.execute("INSERT INTO lesson_question_attempts (id,user_id,lesson_id,block_id,selected_option_id,correct) VALUES (?,?,?,?,?,?)",[createId(),userId,input.lessonId,input.blockId,input.selectedOptionId,correct]);return{correct,explanation:correct?payload.explanation??null:null};}

export async function completeLesson(userId:string,lessonId:string,now=new Date()){return withTransaction(async connection=>{const[lessonRows]=await connection.execute<RowDataPacket[]>(`SELECT l.id,l.xp_reward xpReward,c.id courseId,e.id enrollmentId,u.id unitId,usr.timezone FROM lessons l JOIN course_units u ON u.id=l.unit_id AND u.status='published' JOIN course_levels lv ON lv.id=u.level_id AND lv.status='published' JOIN courses c ON c.id=lv.course_id AND c.status='published' JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='active' JOIN users usr ON usr.id=e.user_id AND usr.role='student' AND usr.status='active' WHERE l.id=? AND l.status='published' FOR UPDATE`,[userId,lessonId]);const lesson=lessonRows[0];if(!lesson)throw new Error("LESSON_NOT_AVAILABLE");const[seqRows]=await connection.execute<RowDataPacket[]>(sequenceSql,[userId,lesson.courseId]);const items=sequence(seqRows);if(!canAccessLesson(items,lessonId))throw new Error("LESSON_LOCKED");const wasCompleted=items.find(item=>item.id===lessonId)?.completed??false;
    const[requiredQuestions]=await connection.execute<RowDataPacket[]>("SELECT id FROM lesson_blocks WHERE lesson_id=? AND block_type='multiple_choice' AND required=true AND status='published'",[lessonId]);for(const question of requiredQuestions){const[passed]=await connection.execute<RowDataPacket[]>("SELECT id FROM lesson_question_attempts WHERE user_id=? AND lesson_id=? AND block_id=? AND correct=true LIMIT 1",[userId,lessonId,question.id]);if(!passed[0])throw new Error("REQUIRED_QUESTION_INCOMPLETE");}
    if(!wasCompleted){await connection.execute("INSERT INTO lesson_progress (id,user_id,lesson_id,status,started_at,completed_at) VALUES (?,?,?,'completed',?,?,?) ON DUPLICATE KEY UPDATE status='completed',started_at=COALESCE(started_at,VALUES(started_at)),completed_at=COALESCE(completed_at,VALUES(completed_at))",[createId(),userId,lessonId,now,now]);await connection.execute("INSERT IGNORE INTO xp_transactions (id,user_id,amount,reason,source_type,source_id) VALUES (?,?,?,'lesson_completion','lesson',?)",[createId(),userId,Number(lesson.xpReward),lessonId]);const date=localDateKey(now,String(lesson.timezone));await connection.execute("INSERT INTO daily_learning_activities (id,user_id,activity_date,timezone,minutes,lessons_completed,words_learned) VALUES (?,?,?,?,0,1,0) ON DUPLICATE KEY UPDATE lessons_completed=lessons_completed+1",[createId(),userId,date,lesson.timezone]);}
    const completedItems=items.map(item=>item.id===lessonId?{...item,completed:true}:item),next=firstIncompleteLesson(completedItems);await connection.execute("UPDATE course_enrollments SET current_lesson_id=?,completed_at=? WHERE id=?",[next,next?null:now,lesson.enrollmentId]);return{completed:true,firstCompletion:!wasCompleted,xpAwarded:wasCompleted?0:Number(lesson.xpReward),nextLessonId:next};});}
