import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { calculateStreak,isDuplicateXpError,localDateKey,onboardingSchema,profileSchema,progressPercent,recommendStartingPoint,settingsSchema } from "@/server/learner/validation";

describe("Phase 2 learner foundation",()=>{
  it("validates the complete onboarding contract and student modes",()=>{expect(onboardingSchema.safeParse({arabicLevel:"complete_beginner",learningGoal:"quranic",dailyGoalMinutes:15,studentMode:"child"}).success).toBe(true);expect(onboardingSchema.safeParse({arabicLevel:"expert",learningGoal:"other",dailyGoalMinutes:12,studentMode:"admin"}).success).toBe(false);expect(settingsSchema.safeParse({interfaceLocale:"bn",studentMode:"standard",dailyGoalMinutes:30}).success).toBe(true);});
  it("recommends deterministic, replaceable starting points without progress",()=>{expect(recommendStartingPoint("complete_beginner")).toBe("arabic_alphabet");expect(recommendStartingPoint("knows_some_letters")).toBe("letter_review");expect(recommendStartingPoint("reads_slowly")).toBe("reading_basics");expect(recommendStartingPoint("intermediate")).toBe("intermediate_review");});
  it("uses the learner timezone for local activity dates",()=>{const instant=new Date("2026-01-01T20:30:00Z");expect(localDateKey(instant,"Asia/Dhaka")).toBe("2026-01-02");expect(localDateKey(instant,"America/New_York")).toBe("2026-01-01");});
  it("calculates streaks without creating activity on refresh",()=>{expect(calculateStreak(["2026-08-28","2026-08-27","2026-08-26"],"2026-08-28")).toBe(3);expect(calculateStreak(["2026-08-27","2026-08-26"],"2026-08-28")).toBe(2);expect(calculateStreak([],"2026-08-28")).toBe(0);});
  it("aggregates progress honestly",()=>{expect(progressPercent(0,0)).toBe(0);expect(progressPercent(2,5)).toBe(40);expect(progressPercent(7,5)).toBe(100);});
  it("validates profile fields without accepting roles",()=>{const result=profileSchema.safeParse({fullName:"Learner One",displayName:"Learner",nativeLanguageCode:"bn",learningLanguageCode:"ar",country:"BD",timezone:"Asia/Dhaka",learningGoal:"general",dailyGoalMinutes:10,role:"super_admin"});expect(result.success).toBe(true);if(result.success)expect("role" in result.data).toBe(false);});
  it("classifies duplicate XP awards",()=>{expect(isDuplicateXpError({code:"ER_DUP_ENTRY"})).toBe(true);expect(isDuplicateXpError(new Error("other"))).toBe(false);});
  it("keeps enrollment, XP, and learner updates server constrained",()=>{const migration=readFileSync("prisma/migrations/20260828000300_phase2_learner_experience/migration.sql","utf8");const service=readFileSync("src/server/learner/service.ts","utf8");expect(migration).toContain("xp_transactions_user_id_source_type_source_id_reason_key");expect(migration).toContain("daily_learning_activities_user_id_activity_date_key");expect(service).toContain("INSERT IGNORE INTO course_enrollments");expect(service).toContain("WHERE id=? AND role='student' AND status='active'");expect(service).toContain("JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=?");expect(service).toContain('state:"completed"|"current"|"available"|"locked"');});
  it("forces authenticated learner route groups to render per request",()=>{for(const file of ["src/app/learn/layout.tsx","src/app/profile/layout.tsx","src/app/settings/layout.tsx"]){expect(readFileSync(file,"utf8")).toContain('dynamic="force-dynamic"');}});
});
