import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
import {arabicLetterSchema,parseLessonBlock,phraseSchema,vocabularySchema} from "@/server/content/schemas";import {parseExercise,publicPayload} from "@/server/exercises/contracts";
import {canAccessLesson,firstIncompleteLesson,nextLessonId} from "@/server/content/progression";
import {progressPercent} from "@/server/learner/validation";
const migration=readFileSync("prisma/migrations/20260829000100_phase3_arabic_lesson_engine/migration.sql","utf8");
const service=readFileSync("src/server/content/lesson-service.ts","utf8");

describe("Phase 3 content engine",()=>{
  it("validates supported lesson blocks and rejects unknown or malformed payloads",()=>{expect(parseLessonBlock("heading",{text:"স্বাগতম"})?.type).toBe("heading");expect(parseLessonBlock("exercise",{exerciseKey:"intro-reading-direction"})?.type).toBe("exercise");expect(parseLessonBlock("script",{html:"<script>"})).toBeNull();});
  it("keeps authoritative multiple-choice answers out of public payloads",()=>{const exercise=parseExercise("multiple_choice",{options:[{id:"left",label:"বাম"},{id:"right",label:"ডান"}],correctOptionId:"right"},{maxScore:100},{mode:"unlimited",mustCorrectToContinue:true});expect(exercise).not.toBeNull();const payload=publicPayload(exercise!.type,exercise!.payload);expect(payload).toEqual({options:[{id:"left",label:"বাম"},{id:"right",label:"ডান"}]});expect("correctOptionId" in payload).toBe(false);});
  it("validates Arabic letter, vocabulary, and phrase records",()=>{expect(arabicLetterSchema.safeParse({stableKey:"tha",character:"ث",arabicName:"ثَاء",banglaPronunciation:"ছা (আনুমানিক)",englishTransliteration:"thā",banglaSoundExplanation:"বাংলায় ঠিক সমান ধ্বনি নেই।",isolatedForm:"ث",initialForm:"ثـ",medialForm:"ـثـ",finalForm:"ـث",makhrajRegion:"tongue",makhrajSubregion:"tip between incisors",makhrajExplanationBangla:"দাঁতের মাঝখানে",pronunciationTipBangla:"স বানাবেন না",position:4}).success).toBe(true);expect(vocabularySchema.safeParse({stableKey:"bab",word:"باب",wordWithDiacritics:"بَاب",banglaPronunciation:"বাব",banglaMeaning:"দরজা",englishMeaning:"door",transliteration:"bāb",partOfSpeech:"noun",root:null,difficulty:1,exampleSentence:"هٰذَا بَابٌ"}).success).toBe(true);expect(phraseSchema.safeParse({stableKey:"salam",text:"السلام عليكم",textWithDiacritics:"السَّلَامُ عَلَيْكُمْ",banglaPronunciation:"আস্-সালামু আলাইকুম",banglaMeaning:"শান্তি বর্ষিত হোক",englishMeaning:"Peace be upon you",usageNoteBangla:"অভিবাদন",difficulty:1}).success).toBe(true);});
  it("unlocks only the first incomplete lesson while preserving completed access",()=>{const items=[{id:"one",completed:true},{id:"two",completed:false},{id:"three",completed:false}];expect(firstIncompleteLesson(items)).toBe("two");expect(canAccessLesson(items,"one")).toBe(true);expect(canAccessLesson(items,"two")).toBe(true);expect(canAccessLesson(items,"three")).toBe(false);expect(nextLessonId(items,"two")).toBe("three");});
  it("calculates course progress from completed published lesson counts",()=>{expect(progressPercent(3,18)).toBe(17);expect(progressPercent(18,18)).toBe(100);});
  it("filters every published hierarchy level from dashboard progress",()=>{const learnerService=readFileSync("src/server/learner/service.ts","utf8");expect(learnerService).toContain("u.status='published'");expect(learnerService).toContain("lv.status='published'");expect(learnerService).toContain("ls.status='published'");});
  it("seeds a coherent Unicode course and all required foundation content",()=>{for(const value of ["ا","ب","ت","ث","ج","ح","خ","د","ذ","ر","بَ","بِ","بُ","السَّلَامُ عَلَيْكُمْ","শুকরান"]){expect(migration).toContain(value);}expect(migration.match(/'c3_l\d\d'/g)?.length).toBeGreaterThanOrEqual(18);});
  it("uses stable keys and idempotent seed statements",()=>{expect(migration).toContain("ON DUPLICATE KEY UPDATE");expect(migration).toContain("arabic_letters_stable_key_key");expect(migration).toContain("vocabulary_items_stable_key_key");expect(migration).toContain("phrases_stable_key_key");});
  it("retrieves only enrolled and fully published content",()=>{expect(service).toContain("JOIN course_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='active'");expect(service).toContain("c.status='published'");expect(service).toContain("u.status='published'");expect(service).toContain("lv.status='published'");expect(service).toContain("l.status='published'");expect(service).toContain("status='published' ORDER BY position");});
  it("delegates exercise scoring to the reusable server engine",()=>{expect(service).toContain("getPublicExercises");expect(service).not.toContain("correctOptionId");expect(service).not.toContain("lesson_question_attempts");});
  it("completes lessons transactionally with duplicate XP prevention",()=>{expect(service).toContain("INSERT IGNORE INTO xp_transactions");expect(service).toContain("'lesson_completion','lesson'");expect(service).toContain("COALESCE(completed_at,VALUES(completed_at))");expect(service).toContain("lessons_completed=lessons_completed+1");expect(service).toContain("UPDATE course_enrollments SET current_lesson_id");});
  it("keeps earlier migrations untouched by locking their known content",()=>{expect(readFileSync("prisma/migrations/20260828000100_installer_foundation/migration.sql","utf8")).toContain("CREATE TABLE `app_settings`");expect(readFileSync("prisma/migrations/20260828000200_phase1_core_domain/migration.sql","utf8")).toContain("course_ar_foundation_bn");expect(readFileSync("prisma/migrations/20260828000300_phase2_learner_experience/migration.sql","utf8")).toContain("lesson_progress");});
});
